#!/bin/sh

BASE_URL=https://raw.githubusercontent.com/paulera/setup-tinycore-scripts/master

# tce-load -w -i openssl.tcz
for i in $(wget -qO- https://api.github.com/repos/paulera/setup-tinycore-scripts/contents/ | cat | grep \"download_url\" | sed 's/[ ]\+"download_url": "\(.*\)"[,]*/\1/g'); do
	wget $i
done
#wget $BASE_URL/tin
